### ISSUE TITLE
Getting C_Login CKR_FUNCTION_NOT_SUPPORTED for Windows CryptoAPI

### ISSUE THREAD

**Issue by abrbhat** [PeculiarVentures/graphene#109]
I am trying to access an ePassAuto2003 smartcard through Windows CryptoAPI
Trying to run an example listed in readme:
```
var graphene = require("graphene-pk11");
var Module = graphene.Module;

var lib = "pvpkcs11.dll";

var mod = Module.load(lib, "Windows CryptoAPI");
mod.initialize();

var slot = mod.getSlots(0);
if (slot.flags & graphene.SlotFlag.TOKEN_PRESENT) {
    var session = slot.open();
    session.login("12345");
    
    var k = session.generateKey(graphene.KeyGenMechanism.AES, {
        "class": graphene.ObjectClass.SECRET_KEY,
        "token": false,
        "valueLen": 256 / 8,
        "keyType": graphene.KeyType.AES,
        "label": "My AES secret key",
        "private": true
    });
    
    console.log("Key.handle:", k.handle);                 // Key.handle: 2
    console.log("Key.type:", graphene.KeyType[k.type]);   // Key.type: AES
    
    session.logout();
    session.close();
}
else {
    console.error("Slot is not initialized");
}

mod.finalize();
```

I get the following error:
```
W:\Algopixel Local\graphene-test\node_modules\graphene-pk11\build\session.js:43
        this.lib.C_Login(this.handle, userType, pin);
                 ^

Error: CKR_FUNCTION_NOT_SUPPORTED:84
    at Error (native) PKCS11::C_Login:372
    at Session.login (W:\Algopixel Local\graphene-test\node_modules\graphene-pk11\build\session.js:43:18)
    at Object.<anonymous> (W:\Algopixel Local\graphene-test\generate-aes-key.js:12:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

What is the correct way to do this via graphene?

**Comment by microshine** [comment]
You don't need to use `C_Login` function, cause PVPKCS11 flag `LOGIN_REQUIRED` is disabled. I'd like to suggest you using [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11) module. It implements WebCrypto interface and based on `graphene-pk11`.

https://github.com/PeculiarVentures/node-webcrypto-p11/blob/0a1506d2f4e4865768c7db55617b37ea5f51c668/src/crypto.ts#L85

I'm using PVPKCS11 with `node-webcrypto-p11` in [webcrypto-local](https://github.com/PeculiarVentures/webcrypto-local) for [Fortify](https://fortifyapp.com/) ([source](https://github.com/PeculiarVentures/fortify))

https://github.com/PeculiarVentures/webcrypto-local/blob/32b6ba6e8b77e1f375af5c577d6cc6a996f96b85/packages/server/src/services/key_storage.ts#L71

**Comment by abrbhat** [comment]
Thanks @microshine. Will study the source. Closing the issue now.
