### ISSUE TITLE
Ubuntu 15.10 install issues

### ISSUE THREAD

**Issue by jbdatko** [PeculiarVentures/graphene#33]
I've experienced a few issues trying to get this library going on Ubuntu 15.10:

- The home readme says to install `softhsm` but you actually need `softhsm2` to get the `softhsm2-util`.
- There seems to be some permission issues with softhsm2, mainly the token dirs are rwx for the root user only. I really not really your code's issue but I have to run softhsm2-util as root :( to create a token.
- Lastly, I `npm install graphene-pk11` and then tried to run an example (the slots example). I had to change the require from pkcs11 to `graphene-pk11` and then I get this error:
```
/tmp/soft/node_modules/graphene-pk11/node_modules/ref/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /tmp/soft/node_modules/graphene-pk11/node_modules/ref/build/Release/binding.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/tmp/soft/node_modules/graphene-pk11/node_modules/ref/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/tmp/soft/node_modules/graphene-pk11/node_modules/ref/lib/ref.js:5:47)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

```
node --version
v0.12.7
```

**Comment by rmhrisk** [comment]
I suspect if you ran the cli as root it would work, I know this is bad form. The issue appears to be an inability to load the pkcs11 library (likley caused by perms). Ill setup a repro wehen i have a few min and see how to modift softhsm perms to make it work as not root.

**Comment by rmhrisk** [comment]
We fixed the readme issues you called out.

I have not yet had a chance to try to reproduce the issue, but I would start checking permissions on the files in this post : https://bugzilla.redhat.com/show_bug.cgi?id=1098188

**Comment by rmhrisk** [comment]
Updated the readme with how to set perms
