### ISSUE TITLE
PKCS and CardOS11

### ISSUE THREAD

**Issue by Johnz86** [PeculiarVentures/graphene#74]
Hello I try to use this library to work with cardos11.dll
I tried to use the examples like this:
```
var pkcs11js = require("pkcs11js");
var path = require("path");

var lib = path.resolve("C:\\Windows\\SysWOW64\\cardos11.dll");
var pkcs11 = new pkcs11js.PKCS11();
pkcs11.load(lib);
 
pkcs11.C_Initialize();
 
try {
    // Getting info about PKCS11 Module 
    var module_info = pkcs11.C_GetInfo();
 
    // Getting list of slots 
    var slots = pkcs11.C_GetSlotList(true);
    var slot = slots[0];
 
    // Getting info about slot 
    var slot_info = pkcs11.C_GetSlotInfo(slot);
    // Getting info about token 
    var token_info = pkcs11.C_GetTokenInfo(slot);
 
    // Getting info about Mechanism 
    var mechs = pkcs11.C_GetMechanismList(slot);
    var mech_info = pkcs11.C_GetMechanismInfo(slot, mechs[0]);
 
    var session = pkcs11.C_OpenSession(slot, pkcs11js.CKF_RW_SESSION | pkcs11js.CKF_SERIAL_SESSION);
 
    // Getting info about Session 
    var info = pkcs11.C_GetSessionInfo(session);
    pkcs11.C_Login(session, 1, "password");
 
    /**
    * Your app code here
    */
    
    pkcs11.C_Logout(session);
    pkcs11.C_CloseSession(session);
}
catch(e){
    console.error(e);
}
finally {
    pkcs11.C_Finalize();
}
```
Which fails with:
```
$ node index.js
C:\GIT\PKCS\index.js:6
pkcs11.load(lib);
       ^

Error: Win32 error 193
    at Error (native) PKCS11::Load:129
    at Error (native)
    at Object.<anonymous> (C:\GIT\PKCS\index.js:6:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```
Could anyone help what I am doing wrong?

**Comment by microshine** [comment]
[Windows errros](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx)

__ERROR_BAD_EXE_FORMAT__
193 (0xC1)
%1 is not a valid Win32 application.

Does your `cardos11.dll` has the same arch as NodeJS?

**Comment by Johnz86** [comment]
Sorry I added issue for wrong librarry :) it is for pkcs11js lol. You can close this here :)

**Comment by microshine** [comment]
I think that I'll give the same answer in pkcs11js

**Comment by rmhrisk** [comment]
@Johnz86 when trying to load cardos11.dll the loader decided it is not a valid win32 binary. It could be the file is corrupt or maybe compiled with a different architecture than the host it is being run on.

Closing this since thats clearly whats happening and it is in wrong repo.
